#---standard pioneer footprint---
#---(in meters)---

robot_radius: 0.250
#footprint: [[-0.125, 0.125], [-0.125, -0.125], [0.125, -0.125], [0.125, 0.125]]
#footprint_padding: 0.125

transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 1.0
 raytrace_range: 2.0
 inflation_radius: 0.5
 #track_unknown_space: false
 #combination_method: 1

 observation_sources: laser_scan_sensor #pointcloud_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
 #pointcloud_sensor: {data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}


#inflation_layer:
  #enabled:              true
  #cost_scaling_factor:  5.0 # exponential rate at which the obstacle cost drops off (default: 10)
  #inflation_radius:     0.5 # max. distance from an obstacle at which costs are incurred for planning paths.

#static_layer:
 # enabled:              true
  #map_topic:            "/map"
