global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.5
  publish_frequency: 0.5
  static_map: true
  #transform_tolerance: 0.5
  #width: 20.0
  #height: 20.0
  #resolution: 0.05
  #rolling_window: false
  #plugins:
   # - {name: static_layer,            type: "costmap_2d::StaticLayer"}
   # - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
   # - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
