robot:
 # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

 # Position Controllers ---------------------------------------
  camera_joint_controller:
    type: position_controllers/JointPositionController
    joint: camera_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}